apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-env-to-pods
spec:
  rules:
  - name: add-env-label-to-pod
    match:
      all:
      - resources:
          kinds:
          - Pod
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            env: staging