apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deployment-require-replicas-1
  annotations:
    policies.kyverno.io/title: Require Replcas Count 1
    policies.kyverno.io/category: Lab-policy
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Deployment, Labels
    policies.kyverno.io/description: >-
      This simple policy checks if deployemnt with `env:dev` label has replica count = 1, otherwise denies creation
spec:
  validationFailureAction: Enforce
#  background: false
  rules:
    - name: check-for-replicas
      match:
        any:
          - resources:
              kinds:
                - Deployment
          # - resources:
          #     kinds:
          #       - Deployment/scale
      preconditions:
        any:
        - key: "{{ request.object.metadata.labels.env }}"
          operator: Equal
          value: dev
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kyverno
      validate:
        message: "Replica count should be equal to 1"
        pattern:
          spec:
            replicas: 1