# helm install kyverno-policies --namespace kyverno kyverno/kyverno-policies
# https://artifacthub.io/packages/helm/kyverno/kyverno-policies
podSecurityStandard: "restricted"
#include additional policy to security standard above
customPolicies:
  - apiVersion: kyverno.io/v1
    kind: ClusterPolicy
    metadata:
      name: test-values-custom
      annotations:
        policies.kyverno.io/title: Require Annotations
        policies.kyverno.io/category: Lab-policy
        policies.kyverno.io/severity: medium
        policies.kyverno.io/subject: Pod, Annotation
        policies.kyverno.io/description: >-
          This simple policy checks for annotation `corp.org/department` with non-empty during the pod creation, denies creation if not found
    spec:
      validationFailureAction: Enforce
      rules:
        - name: check-for-annotations
          match:
            any:
              - resources:
                  kinds:
                    - Pod
          exclude:
            any:
              - resources:
                  namespaces:
                    - kube-system
                    - kyverno
          validate:
            message: "Annotation `corp.org/department` is required"
            pattern:
              metadata:
                annotations:
                  corp.org/department: "?*"