apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-vulnerabilities
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: checking-vulnerability-scan-not-older-than-one-hour
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "*"
          attestations:
            - type: https://cosign.sigstore.dev/attestation/vuln/v1
              conditions:
                - all:
                    - key: "{{ time_since('', '{{metadata.scanFinishedOn}}', '') }}"
                      operator: LessThanOrEquals
                      value: "1h"
              attestors:
                - count: 1
                  entries:
                    - keys:
                        publicKeys: |
                          -----BEGIN PUBLIC KEY-----
                          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEdVEFpsweK95l/4axNj5de24bk9WP
                          Mm+x8P5PIjX4G4t81Mok7CFKkUiyn+e75VjtcYK4ZuMf/I4T60umV5toJQ==
                          -----END PUBLIC KEY-----
