apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  namespace: default
  labels:
    run: nginx
    name: nginx-pod-1
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8081  # disallow-host-ports
      securityContext:
        capabilities:
          add: ["NET_ADMIN"] # disallow-capabilities
        privileged: true       # disallow-privileged-container
  hostPID: true                # disallow-host-namespaces
