apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kyverno-rules
  namespace: kyverno
  labels:
    release: prometheus
spec:
  groups:
    - name: kyverno.rules
      rules:
        - alert: KyvernoPolicyFailuresHigh
          expr: increase(kyverno_policy_rule_fail_total[5m]) > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "We have failures!"
            description: "We have at least one failed policy for the last 5 minutes"
