apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: app
  labels:
    run: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 80 
      securityContext:
        capabilities:
          add: ["NET_ADMIN"]  
        privileged: true      
  hostPID: true  # disallow-host-namespaces
